#!/usr/bin/env bash

docker image build -t charliecalvert/call-you=rang .
docker container run --name call-you=rang -d -p 30025:30025 charliecalvert/call-you=rang
docker exec -it call-you=rang /bin/bash
